"""Remove role from game_sessions

Revision ID: 2f05a5310f15
Revises: ea65c0110324
Create Date: 2026-03-15 08:37:45.577434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f05a5310f15'
down_revision = 'ea65c0110324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
