"""Expand schema: GameRound, card impacts, session role

Revision ID: f2ccc296a474
Revises: 928eb8280d64
Create Date: 2026-03-15 07:32:18.690396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2ccc296a474'
down_revision = '928eb8280d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('choice_made', sa.String(length=1), nullable=False),
    sa.Column('biosphere_after', sa.Integer(), nullable=False),
    sa.Column('society_after', sa.Integer(), nullable=False),
    sa.Column('economy_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('choices')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('a_biosphere', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('a_society', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('a_economy', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b_biosphere', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b_society', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('b_economy', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.String(length=20), nullable=False))

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('final_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('biosphere',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('society',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('economy',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('economy',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('society',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('biosphere',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('ended_at')
        batch_op.drop_column('final_score')
        batch_op.drop_column('role')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('phase')
        batch_op.drop_column('role_type')
        batch_op.drop_column('b_economy')
        batch_op.drop_column('b_society')
        batch_op.drop_column('b_biosphere')
        batch_op.drop_column('a_economy')
        batch_op.drop_column('a_society')
        batch_op.drop_column('a_biosphere')

    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('choice_made', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('biosphere_impact', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('society_impact', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('economy_impact', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('choices_card_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], name=op.f('choices_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('choices_pkey'))
    )
    op.drop_table('game_rounds')
    # ### end Alembic commands ###
